name: Spring Core - Tests
on:
  push:
    branches: 
     - main  
     - '*-*[0-9]'
jobs:
  test:
    name: Test - Unit & Integration & SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'  # Consider specifying a distribution
      - name: Unit & Integration Tests
        run: mvn -B verify
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: Slack WebHook
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: 'repo,author,commit,author,workflow'  # fixed quotes around fields
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Sonar
        if: success()
        run: mvn -B sonar:sonar -Dsonar.projectKey=es.upm.miw:betca-tpv-core -Dsonar.organization=miw-upm-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
